yatube/posts/urls.py
# posts/urls.py

from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:path>/',
        views.group_list,
        name='group_list'
        )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts'))
]

yatube/posts/models.py
# posts/models.py

from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    address = models.SlugField()
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='group'
    )

yatube/posts/views.py
# posts/views.py

from django.shortcuts import render, get_object_or_404
# Импортируем модели, чтобы обратиться к ним
from .models import Post, Group


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    description = 'Это главная страница проекта Yatube'
    # В переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию
    # (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'title': title,
        'description': description,
        'posts': posts
    }
    return render(
        request,
        template,
        context,
        )


def group_list(request, path):
    template = 'posts/group_list.html'
    title = 'Лев Толстой – зеркало русской революции.'
    description = 'Здесь будет информация о группах проекта Yatube'
    group_name = get_object_or_404(Group, address=path)
    posts = Post.objects.filter(group=group_name).order_by('-pub_date')[:10]
    context = {
        'title': title,
        'description': description,
        'group_name': group_name,
        'posts': posts
    }
    return render(request, template, context)

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% load static %}       
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Контент не подвезли :(
      {% endblock %}
    </title>   
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- templates/includes/footer.html -->
<!DOCTYPE html>
<html lang="ru">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!-- templates/includes/header.html -->
<!DOCTYPE html>
<html lang="ru">
{% load static %}
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
  </nav>

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>{{ description }}</h1>
    {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </div>
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>{{ description }}</h1>
    {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>    
    {% if post.group is not null %}
    <a href="{% url 'posts:group_list' post.group.address %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </div>
{% endblock %}